name: my_log
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.4.0"

# Add regular dependencies here.
dependencies:
  # logging: ^1.1.1
  logger: 2.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
